### ISSUE TITLE
Website with given name StartStopVM already exists

### ISSUE THREAD

**Issue by schottky81** [microsoft/startstopv2-deployments#11]
Hi,

Deployment failed with 1 error (conflict) for StartStopVM of type Microsoft.Web/sites:
"Website with given name StartStopVM already exists."

![image](https://user-images.githubusercontent.com/10754366/122942744-b8811100-d376-11eb-93c8-3052bc34a355.png)

**Comment by parojasmsft** [comment]
Hi schottky81,

That error typically occurs due to another subscription having that same name. This subscription is not one owned by you but by the start/stop community in general. Please try to use another name that is unique.

**Comment by balas77** [comment]
Hi schottky81 - 

- We have provided the help text on this property (as below). The name should be unique globally hence you're getting this error due to the name already taken. 
![image](https://user-images.githubusercontent.com/64924532/123006927-422be100-d36d-11eb-8846-88982c10b599.png)
- Please make sure you delete this RG and freshly deploy it or if you want to redeploy this, please make sure you choose the parent template name (starts with "Microsoft_***") to redeploy. 
- Please don't redeploy the template "StartStop_Automation" as this is child or nested template which will only deploy the V2 solution **partially**.   

Please dont hesitate to reach us if you need further help on this.

**Comment by schottky81** [comment]
Hi parojasmsft and balas77,

Thank you very much for your replies. I have deleted the RG and redeployed with a unique name for "Azure Function App Name" and the deployment went well this time.
I was able to schedule stop and start on VMs for WVD.
Thank you again.

**Comment by parojasmsft** [comment]
Glad to hear the issue was resolved.
