### ISSUE TITLE
How to deploy this solution using BICEP ?

### ISSUE THREAD

**Issue by rajsshah86** [microsoft/startstopv2-deployments#37]
1. I want to automate the process of deploying the solution template. Can you guide on how to do this? 
I can see that I can download the template while deploying the solution from portal. Can I simply convert that ARM template to bicep and automate it ?

2. I can see that function app uses basis comsumption plan . I want to have private endpoint and VNET integration for function app . Can I upgrade the app service plan to premium . Also if I enable privateendpoint and VNET integration in functionapp , will the logic app be able to contact function app ( HTTP trigger) ?? .

**Comment by awaadhwa** [comment]
Hi, what is your intent with these actions? We can guide you from there after we have more context.

**Comment by rajsshah86** [comment]
1. I want to automate the process by creating a shared module for deploying this solution using Bicep so that app team can use it . I do not want to go to portal and click stuff to make this work.

2. Our security team wants that n/w traffic should not go out to public n/w . I want to understand how the communication happens b/w  logic app --> function app --> stop/start vm

**Comment by balas77** [comment]
@rajsshah86 - Are you trying to deploy our solution along with any of your existing package? Not able to understand the use case. Why you need to automate this deployment? I believe if you need to use our solution to start and stop the VMs you have to deploy this only once hence trying to understand your ask here.

Regarding the private endpoint/VNET, we haven't tried this scenario. Are you seeing any issues with the default setup and hence moving towards VNET integration? You can also upgrade to premium plan but you should also consider the cost factor and the purpose of being in consumption plan should suffice to perform the start and stop operations. 

Regarding the communication between logic app to function app is via function keys which is provided by the function framework and pretty much internal and not distributed externally and you cant access it from outside. Also the communication from function app to VM will be via managed identity.

**Comment by rajsshah86** [comment]
@balas77 : We as a central team provides the module which can be used by entire organisation to deploy resources on the azure. We do not want to install this solution via portal but rather than via module which internally uses ARM or BICEP to deploy stuff.
I already tried downloading the  ARM TEMPLATE while deploying the solution via portal. However I am stuck because the ARM template uses _artifactsLocation_ parameter as _deployment().properties.templateLink.uri_   . Because of this I get below error:
_##[error]Deployment template validation failed: 'The template resource 'artifactsLocation' at line '1' and column '2740' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'._


2. In the current solution , both logic app and function app are open to INTERNET. I know one however needs key to trigger functionapp . But as per our Security Control Framework, we want to keep everything within our own virtual n/w.  Any suggestion on how to achieve this ?

**Comment by balas77** [comment]
@rajsshah86 - Please see my comments.

#1 - Currently the template is packed and published inside the Azure marketplace so you cannot use this directly. You have to deploy from the marketplace. 

#2 - We haven't checked our solution using VNET and not sure how this will even work inside the VNET since we do compute API calls which needs open network. I have to check on this.

**Comment by ericqms** [comment]
Hi @rajsshah86 

We have seen a few failed deployments last week that had some similarities and had us wondering if they might have been from the issues you are experiencing. Since reaching out to customers is an area that is difficult for us, was wondering if you could confirm if the failed deployments are yours. The subscription id that we see the failures in starts with fd6c. Is this your subscription?

Thanks,
Eric Q.

**Comment by ReneRebsdorf** [comment]
+1 For making this available as a template.

Previously I have deployed [this solution from Microsoft](https://github.com/microsoft/MSITARM/tree/master/ARO-Toolkit-Marketplace) using ARM 
Would be great if similar was possible with this solution

**Comment by ktuuliainen** [comment]
Agree would beneficial to have the solution available as a template and be able to deploy it using DevOps Pipeline/GitHub Actions.

**Comment by rajsshah86** [comment]
> Hi @rajsshah86
> 
> We have seen a few failed deployments last week that had some similarities and had us wondering if they might have been from the issues you are experiencing. Since reaching out to customers is an area that is difficult for us, was wondering if you could confirm if the failed deployments are yours. The subscription id that we see the failures in starts with fd6c. Is this your subscription?
> 
> Thanks, Eric Q.

@ericqms : Yes , that belongs to our subscription. We were trying to deploy it as a CODE.

**Comment by AsbjornHest** [comment]
Agreed, it would be really great to be able to deploy this through DevOps

**Comment by AsbjornNielsen** [comment]
Agreed. It would be really great to be able to deploy this through DevOps pipelines

**Comment by balas77** [comment]
You cannot achieve this via DevOps pipeline since we have mapped the GitHub "**Deploy to Azure**" button to our package directly from the Azure marketplace item (to have better validations on user inputs). 

If you're trying to deploy our offer in all of your subscriptions via DevOps then it is not needed i.e. deploying our offer in any one subscription should capable to manage VMs across multiple subscriptions.

**Comment by ktuuliainen** [comment]
Use case for automating the deployment (e.g. using DevOps pipeline or similar) as I see:

Providing the solution as a toolkit, deployed during subscription provisioning when a team is onboarded to Azure. Sure one instance of the solution can be used for multiple subscriptions by that team (if they have multiple subscriptions). 

But in a situation where there are multiple teams having their subscriptions (e.g. subscription democratization), then a decentralized deployment of the start/stop solution might be a better option (e.g. to segregation of whom can have access to define the schedules).

Depending on an organizations model for access teams might not have the permissions to deploy the solution by themselves (e.g. for example missing permissions to to RBAC assignments). Yet again a use case for automation through pipeline. 

And lastly in general be able to deploy solutions through code instead of having to click in a portal.

**Comment by raldaba** [comment]
Appreciate the use cases you outlined, @ktuuliainen. Thanks for sharing those with us. 

I'll add your comments and points (along with everyone else's) to our team's backlog to discuss for the next iteration of upgrades. This is a scenario that we would like to re-visit due to the large support shown in this thread.

I would like to keep this issue open until we discuss and provide an update, but wanted to let everyone know what was happening.

Thanks again!

**Comment by ReneRebsdorf** [comment]
Thank you for the update @raldaba 

A solution which can be deployed using IaC would be in great alignment with the Cloud Adoption Framework, which advocates Enterprise-Scale.

We would like to use this functionality, but due to the current implementation method have opted for creating our own Azure Pipeline which can scan subscriptions, and perform start/stop of virtual machines based on tags.

**Comment by awaadhwa** [comment]
Hi all, I have taken this in as a feature request and added it to the backlog. Thank you everyone for their inputs!
