### ISSUE TITLE
Idea: Schedule option for specific days

### ISSUE THREAD

**Issue by kathodion** [microsoft/startstopv2-deployments#46]
Hello 
It would be helpful to have the option to specify individual days like Monday-Friday or Monday, Tuesday, and Thursday.
Best regards 
Kathodion

**Comment by svarga-msft** [comment]
Hi, I believe we have this functionality already. If you have week frequency setup on the logic app you can select individual days. Is this different than what you were expecting?
![image](https://user-images.githubusercontent.com/68304251/151231252-e58e00e4-e424-443f-b8d3-714d02e10a69.png)

**Comment by kathodion** [comment]
Hi

Thanks for you fast response.

I do not get that option. Any idea what I should do?
[image: image.png]
Best
Kathodion

Am Mi., 26. Jan. 2022 um 20:18 Uhr schrieb svarga-msft <
***@***.***>:

**Comment by raldaba** [comment]
@kathodion Hi there! Could you confirm if you can see the option "On these days" when you click the "Add New Parameter" drop-down? 
The UI can hide that option sometimes unless you specifically select it. 

If you can't see it in the "Add New Parameter" option, would you be able to share the Azure region you are deploying to?

**Comment by kathodion** [comment]
I made some screenshots. I did not get the "on these days" option.
Any idea?
Thanks, raldaba for your help

![image](https://user-images.githubusercontent.com/10939437/151369453-6fffa8ce-84a2-4dd1-8129-585b130f3997.png)
![image](https://user-images.githubusercontent.com/10939437/151369478-9c13b83f-c9f5-4265-8403-6c753edffb18.png)
![image](https://user-images.githubusercontent.com/10939437/151369694-ba275cf5-ca72-459c-8d71-ece45f3158c3.png)

**Comment by raldaba** [comment]
@kathodion Yeah, it looks like something we would need to check with the Logic App support team, since this looks particularly specific to their UI. If you are able to create a support ticket right there in the portal, that might be the best way to engage the proper support engineers that can diagnose this issue.

We would suggest these values for the support ticket:
Issue type: Technical
Service Type: Logic App
Problem Type: Tools and Management
Problem subtype: Portal

Hope that helps!
