### ISSUE TITLE
Template needs updating to conform to current standards

### ISSUE THREAD

**Issue by Megacotts** [microsoft/startstopv2-deployments#96]
When deployed the solution fails most security policy checks, mainly due to the storage account being gen1 and defaulting to TLS 1.0. Please update this to use gen2 with tls 1.2 default.

**Comment by GeoffMcKimNPS** [comment]
Yes, we have the same issue. Tenant policy requires that storage accounts be restricted to TLS 1.2 and above, and since we cannot use an existing storage account, trying to deploy Start/Stop VMs v2 fails validation. Is there any plan to adjust this? Being able to use an existing storage account would fix the problem. Thank you.

**Comment by jeffw16** [comment]
This has now been addressed. As of early 2024, the latest versions of StartStop V2 use storage accounts that require TLS 1.2 to be used.
